# Generated by Django 4.2.7 on 2023-11-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('operating_hours_start', models.DateTimeField()),
                ('operating_hours_end', models.DateTimeField()),
                ('contact_number', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Cinema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('base_price', models.FloatField()),
            ],
            options={
                'db_table': 'Film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seating_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Hall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('class_coefficient', models.FloatField()),
            ],
            options={
                'db_table': 'Seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('seller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('showtime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Showtime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.film')),
            ],
            options={
                'db_table': 'Film_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.film')),
            ],
            options={
                'db_table': 'Production_country',
                'managed': False,
            },
        ),
    ]
